apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pokedex-templates-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
